import{a as L,i as c,S as w}from"./assets/vendor-5401a4b0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();async function h(o,t,r){let a="https://pixabay.com/api/";const e=await L.get(a,{params:{key:"42490410-91d7fda5db61c0a899b50e1d9",q:o,per_page:r,page:t,orientation:"horizontal",safesearch:!0}});if(console.log(e.data.total),e.status!==200)throw new Error("Image error!");return(await e.data).hits}function m(o){const t=document.querySelector(".gallery"),r=o.map(({webformatURL:a,tags:e,likes:s,views:i,comments:b,downloads:v,largeImageURL:u})=>`<div class="pic-card">
          <a class="gallery-link" href="${u}">
            <img 
              src="${a}"
              data-source="${u}"
              alt="${e}" />
          </a>
          <div class="pic-info">
            <div class="info"><p class="label">Likes</p> <p class="info-label">${s}</p></div>
            <div class="info"><p class="label">Views</p> <p class="info-label">${i}</p></div>
            <div class="info"><p class="label">Comments</p> <p class="info-label">${b}</p></div>
            <div class="info"><p class="label">Downloads</p> <p class="info-label">${v}</p></div>
          </div>
        </div>`).join("");t.insertAdjacentHTML("beforeend",r)}const d=document.querySelector(".input-picstyle"),S=document.querySelector(".search-btn"),g=document.querySelector(".gallery"),l=document.querySelector(".loadmore-btn"),n=document.querySelector(".loader"),f=document.querySelector(".the-end");let y="",p=1;const q=15;S.addEventListener("click",async()=>{g.innerHTML=null;const t=d.value.trim().split(" ").join("+");if(f.classList.add("is-hidden"),y=t,console.log(t),!t){c.error({color:"red",message:"Please fill in the querry, what are you looking for?",position:"center",progressBarColor:"rgb(0, 255, 184)",timeout:2e3});return}n.classList.remove("is-hidden");try{const r=await h(t,p,15);console.log(r),r.length===0?(g.innerHTML=null,l.classList.add("is-hidden"),c.error({color:"yellow",message:"Sorry, there are no images matching your search query. Please try again!",position:"center",progressBarColor:"rgb(0, 255, 184)",timeout:2e3})):(m(r),n.classList.add("is-hidden"),r.length<=14?(l.classList.add("is-hidden"),f.classList.remove("is-hidden")):l.classList.remove("is-hidden"),new w(".pic-card a",{captionsData:"alt",captionDelay:250}).refresh())}catch(r){console.log("Error caught:",r.message),c.error({color:"red",message:"Error while fetching images",position:"center",progressBarColor:"rgb(0, 255, 184)",timeout:2e3})}finally{d.value="";let r=t.split("+").join(" ");d.placeholder=`Last searched for "${r}"`}});l.addEventListener("click",async()=>{n.classList.remove("is-hidden");try{p++;let o=await h(y,p,q);n.classList.add("is-hidden"),m(o);let r=document.querySelector(".pic-card").getBoundingClientRect();window.scrollBy({top:2*r.height,behavior:"smooth"})}catch(o){console.error("Error while fetching images:",o.message)}});
//# sourceMappingURL=commonHelpers.js.map
